package com.cs407_android.ormlab;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EVENT.
 */
public class Event {

    private Long id;
    private String date;
    private String details;
    private Boolean display;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String date, String details, Boolean display) {
        this.id = id;
        this.date = date;
        this.details = details;
        this.display = display;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public Boolean getDisplay() {
        return display;
    }

    public void setDisplay(Boolean display) {
        this.display = display;
    }

    public String toString(){return this.date + " " + this.details;}

}
